= Data Structures and Algorithms
include::.attributes[]


== Books (in English)

Cormen, T., Leiserson, C., Rivest, R., Stein, C. (2009) *Introduction to Algorithms*, 3rd ed. MIT Press. ISBN 978-0-262-03384-8

Sedgewick, R. (1998) *Algorithms in C++, Parts 1-4: Fundamentals, Data Structure, Sorting, Searching*, 3rd ed. Addison-Wesley

Sedgewick, R. (2001) *Algorithms in C++ Part 5: Graph Algorithms*, 3rd ed. Addison-Wesley.

Sedgewick, R.; Wayne, K (2011) *Algorithms*, 4th edition. Addison-Wesley. +
https://algs4.cs.princeton.edu/home/

Skiena, Steven (2008) *The Algorithm Design Manual*, 2nd ed.

Weiss, Mark Allen (2014) *Data Structures and Algorithm Analysis in C++*. ISBN 978-0-13-284737-7

Antti Laaksonen (2018) *Competitive Programmer's Handbook*. +
http://cses.fi/book/index.html

Knuth, Donald (1997) *The Art of Computer Programming*, 3 ed., vol. 1: Fundamental Algorithms. Addison-Wesley.

Knuth, Donald (1997) *The Art of Computer programming*, 3 ed., vol. 2: Seminumerical Algorithms. Addison-Wesley.

Knuth, Donald (1998) *The Art of Computer programming*, 2 ed., vol. 3: Sorting and Searching. Addison-Wesley.

Knuth, Donald (2011) *The Art of Computer Programming, Vol. 4A: Combinatorial Algorithms, Part 1*. Addison-Wesley.

Morin, Pat. *Open Data Structures (in C++)*. +
http://opendatastructures.org/ods-cpp/

Mount, David (1998) *CMSC 251: Algorithms - Lecture Notes*. +
http://www.cs.umd.edu/~meesh/351/mount/251lects.ps



== Books (in Bulgarian)

Седжуик, Р. (2003) *Алгоритми на C*.

Наков, Преслав; Добриков, Панайот (2003) *Програмиране = ++Алгоритми*. ISBN 954-8905-06-X

Амерал, Лендерт (2001) *Алгоритми и структури от данни в С++*. ISBN 954-8495-25-2


== Combinatorial

https://www.nayuki.io/page/next-lexicographical-permutation-algorithm[Next lexicographical permutation algorithm] | Project Nayuki

http://ruslanledesma.com/2016/06/17/why-does-heap-work.html[Why does Heap's algorithm work?] | Ruslan writes code


== Linear data structures

https://research.googleblog.com/2006/06/extra-extra-read-all-about-it-nearly.html|[Extra, Extra - Read All About It: Nearly All Binary Searches and Mergesorts are Broken] | Joshua Bloch (2006)

https://xinok.wordpress.com/2014/08/17/in-place-merge-sort-demystified-2/[In-Place Merge Sort Demystified] | Xinok (2014)

https://en.wikipedia.org/wiki/Introsort[Introsort] | Wikipedia +

https://cs.stackexchange.com/questions/3/why-is-quicksort-better-than-other-sorting-algorithms-in-practice[Why is quicksort better than other sorting algorithms in practice?] | StackExchange


== Binary Trees

https://devblogs.microsoft.com/oldnewthing/20251105-00/?p=111765[Non-recursively deleting a binary tree in constant space: Traversal with parent pointers] | Raymond Chen, The Old New Thing

https://devblogs.microsoft.com/oldnewthing/20251106-00/?p=111771[Non-recursively deleting a binary tree in constant space: Synthesizing the parent pointer] | Raymond Chen, The Old New Thing

https://devblogs.microsoft.com/oldnewthing/20251107-00/?p=111774[Non-recursively deleting a binary tree in constant space: Restructuring the tree] | Raymond Chen, The Old New Thing

https://devblogs.microsoft.com/oldnewthing/20251112-00/?p=111784[Non-recursively deleting a binary tree in constant space: Rotating the tree] | Raymond Chen, The Old New Thing


== Red-Black Tree

https://en.wikipedia.org/wiki/Red%E2%80%93black_tree[Red-Black Tree] | Wikipedia

Robert Sedgewick. *Algorithms in C++, Parts 1-4 Fundamentals, Data Structure, Sorting, Searching*. Chapter Thirteen -- Balanced Trees. Sections "`13.3. Top-Down 2-3-4 Trees`" and "`13.4. Red–Black Trees`".

https://www.baeldung.com/cs/red-black-trees[Introduction to Red-Black Trees] | Michael Krimgen (October 19, 2020)

https://www.educative.io/page/5689413791121408/80001[2-3-4 Trees: A Visual Introduction] (also includes an interactive visualization) | Fahim ul Haq.

https://azrael.digipen.edu/~mmead/www/Courses/CS280/Trees-Mapping2-3-4IntoRB.html[Mapping 2-3-4 Trees into Red-Black Trees] | Matthew Mead

Arne Andersson (1993) *Balanced search trees made simple*. In Proc. Workshop on Algorithms and Data Structures, pages 60--71. Springer Verlag.

http://opendatastructures.org/ods-cpp/[Open Data Structures (in {cpp})] | Pat Morin +
* Chapter 9. http://opendatastructures.org/ods-cpp/9_Red_Black_Trees.html[Red-Black Trees]

https://en.wikipedia.org/wiki/AA_tree[AA tree] | Wikipedia


== Graphs

http://theory.stanford.edu/~amitp/GameProgramming/[Amit`'s pass:[A*] Pages] | Amit Patel

https://www.redblobgames.com/pathfinding/a-star/introduction.html[Introduction to the pass:[A*] Algorithm] | Amit Patel (2016)


== Autocomplete

https://www.futurice.com/blog/data-structures-for-fast-autocomplete/[Data structures for fast autocomplete] | Anti Ajanki (2016)

https://stackoverflow.com/questions/2901831/algorithm-for-autocomplete[Algorithm for autocomplete?] | StackOverflow
 
https://stackoverflow.com/questions/1783652/what-is-the-best-autocomplete-suggest-algorithm-datastructure-c-c[What is the best autocomplete/suggest algorithm,datastructure [{cpp}/C]] | StackOverflow


== Articles on other topics

http://gameprogrammingpatterns.com/data-locality.html[Data Locality] | Bob Nystrom


== Cheat Sheets, Visualizations, etc.

Big-O Algorithm Complexity Cheat Sheet +
http://bigocheatsheet.com/

Data Structures and Algorithms (обяснения и визуализация) +
https://safe-brushlands-32530.herokuapp.com/

Comparison Sorting Algorithms +
https://www.cs.usfca.edu/~galles/visualization/ComparisonSort.html

Sorting Algorithm Animations +
http://www.sorting-algorithms.com/



== Collections of Problems, Competitions, etc.

https://arena.maycamp.com/

https://projecteuler.net/

http://judge.openfmi.net

http://train.usaco.org/usacogate

http://acm.timus.ru/

http://rosalind.info/problems/locations/

https://www.codewars.com

https://codility.com

http://codeforces.com

https://github.com/karan/Projects

http://1001zadachi.com/%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D0%B8-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%B5-%D0%BE%D0%BB%D0%B8%D0%BC%D0%BF%D0%B8%D0%B0%D0%B4%D0%B8-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0.html

http://adventofcode.com/day/1

http://leetcode.com

http://topcoder.com

http://codechef.com

http://interviewbit.com

http://hackerrank.com
