= Architecture
:toc:

== Tools

PlantUML +
http://plantuml.com/

Graphviz +
https://www.graphviz.org/

Visual Paradigm Online +
https://online.visual-paradigm.com/


== Enterprise Architecture

*TOGAF® Standard, Version 9.2* +
The Open Group +
http://pubs.opengroup.org/architecture/togaf9-doc/arch/

*ArchiMate® 3.0.1 Specification* +
The Open Group +
http://pubs.opengroup.org/architecture/archimate3-doc/

*The DoDAF Architecture Framework Version 2.02* +
United States Department of Defense +
https://dodcio.defense.gov/Library/DoD-Architecture-Framework/

*Integrated DEFinitinon (IDEF) Methods* +
http://www.idef.com/

Paul Clements, Felix Bachmann, Len Bass, David Garlan, James Ivers, Reed Little, Paulo Merson, Robert Nord, Judith Stafford (2002). *Documenting Software Architectures: Views and Beyond*, 2nd ed. SEI Series in Software Engineering. ISBN 978-0321552686

Len Bass, Paul Clements, Rick Kazman (2012) *Software Architecture in Practice*, 3rd ed. SEI Series in Software Engineering. ISBN 978-0321815736


== Modeling Languages

*Unified Modeling Language Specification* +
Object Management Group +
https://www.omg.org/spec/UML/

Martin Fowler (2003) *UML Distilled: A Brief Guide to the Standard Object Modeling Language*, 3rd Edition. Addison-Wesley Professional. ISBN 978-0-321-19368-1.


== Other

John Gall (2002). *Systemantics. The Systems Bible*, 3rd ed.

Karl Wiegers; Joy Beatty (2013) *Software Requirements*, 3rd ed. ISBN 9780735679610

Steve McConnell (2004) *Code Complete: A Practical Handbook of Software Construction*, 2nd ed. ISBN 978-0735619678.

Martin Fowler (2018) *Refactoring: Improving the Design of Existing Code*, 2nd ed. ISBN 978-0-13-475759-9.
