= Software Engineering
include::.attributes[]


== Books

Robert C. Martin (2008) *Clean Code: A Handbook of Agile Software Craftsmanship*.

Michael Feathers (2004) *Working Effectively with Legacy Code*.

Martin Fowler (2018) *Refactoring: Improving the Design of Existing Code* (2nd Edition)

Martin Fowler , Kent Beck , et al. (1999) *Refactoring: Improving the Design of Existing Code* (1st Edition)

John Gall (2002). *Systemantics. The Systems Bible*, 3rd ed.

Karl Wiegers; Joy Beatty (2013) *Software Requirements*, 3rd ed. ISBN 9780735679610

Steve McConnell (2004) *Code Complete: A Practical Handbook of Software Construction*, 2nd ed. ISBN 978-0735619678.

== Assorted

https://blog.palantir.com/code-review-best-practices-19e02780015f[Code Review Best Practices] | Palantir Blog

.How To Write Unmaintainable Code | Roedy Green
* https://www.mindprod.com/jgloss/unmain.html
* https://www.doc.ic.ac.uk/~susan/475/unmain.html[Mirror of the essay from 1999]
* https://cs.fit.edu/~kgallagher/Schtick/How%20To%20Write%20Unmaintainable%20Code.html[yet another mirror]

== Processes and methodologies

Robert C. Martin (2019) *Clean Agile: Back to Basics*.

Scrum in under 5 minutes +
https://www.youtube.com/watch?v=2Vt7Ik8Ublw

What Is Scrum | scrum.org +
https://www.scrum.org/resources/what-is-scrum

A Typical Sprint, Play-By-Play | scrum.org +
https://www.scrum.org/resources/blog/typical-sprint-play-play

The official Scrum guide | scrumguides.org +
https://www.scrumguides.org/scrum-guide.html

Agile Project Management | Atlassian +
https://www.atlassian.com/agile/project-management/

* https://www.atlassian.com/agile/project-management/epics-stories-themes[Epics, Stories, Themes, and Initiatives]
* https://www.atlassian.com/agile/project-management/user-stories[User Stories | Examples and Template]
* https://www.atlassian.com/agile/project-management/estimation[What are story points and how do you estimate them?]


== Invariants / Error handling

* Invariants. Object state. Class invariant and process invariant.
* How assert works. When to use assert.

https://en.wikipedia.org/wiki/Exception_safety[Exception Safety Guarantees] | Wikipedia


== Testing

Kent Beck (2002) *Test-Driven Development By Example*.

Maurício Aniche (2022) *Effective Software Testing*. ISBN 9781633439931

Marc Clifton (2013) *Unit Testing Succinctly*. https://www.syncfusion.com/ebooks/unittesting

Kent Beck (2002) *Test-Driven Development By Example.*

https://martinfowler.com/articles/mocksArentStubs.html[Mocks Aren't Stubs] | Martin Fowler

Unit Testing Guidelines | Petroware +
https://petroware.no/unittesting.html

The evolution of Unit Testing Syntax and Semantics +
https://osherove.com/blog/2008/1/17/the-evolution-of-unit-testing-syntax-and-semantics.html

https://haacked.com/archive/2012/01/02/structuring-unit-tests.aspx/[Structuring Unit Tests] | Phil Haack

https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices[.NET Core Unit Testing Best Practices] | Microsoft Docs

https://stackoverflow.com/questions/17441677/c-unit-test-testing-using-template-test-class[How to use template test class in C++ unit test] | Stack Overflow


== Code documentation

https://www.doxygen.nl/manual/docblocks.html[Doxygen Manual]

https://devblogs.microsoft.com/cppblog/doxygen-and-xml-doc-comment-support/[Doxygen and XML Doc Comment support] | Microsoft {cpp} Team Blog

https://www.youtube.com/watch?v=-V_vHZPOZfY[Using Doxygen to document computing projects] | YouTube


== Code formatting / Clang-format

https://clang.llvm.org/docs/ClangFormat.html[Clang-format] | Clang Documentation

https://zed0.co.uk/clang-format-configurator/[clang-format configurator]

https://devblogs.microsoft.com/cppblog/clangformat-support-in-visual-studio-2017-15-7-preview-1/[ClangFormat Support in Visual Studio 2017] | Microsoft {cpp} Team Blog


== Standards and Static Code Analysis

http://www.sevangelatos.com/john-carmack-on-static-code-analysis/[In-Depth: Static Code Analysis] | John Carmack


== Other

https://semver.org/[Semantic Versioning]
